const { zokou } = require("../framework/zokou"); const axios = require("axios");

// =============== FLUX AI =============== zokou({ nomCom: "fluxai", aliases: ["flux", "imagine"], categorie: "ai", reaction: "🚀" }, async (jid, sock, { ms, repondre, arg }) => { const q = arg.join(" "); if (!q) return repondre("❌ Please provide a prompt for the image.");

await repondre("> CREATING IMAGE ...🔥");

try { const url = https://api.siputzx.my.id/api/ai/flux?prompt=${encodeURIComponent(q)}; const { data } = await axios.get(url, { responseType: "arraybuffer" });

await sock.sendMessage(jid, {
  image: Buffer.from(data, "binary"),
  caption: `💸 *Imagine Generated By NEXUS-XMD* 🚀\n✨ Prompt: *${q}*`,
  contextInfo: {
    forwardingScore: 999,
    isForwarded: true,
    forwardedNewsletterMessageInfo: {
      newsletterJid: "120363382023564830@newsletter",
      newsletterName: "🌐𝐁.𝐌.𝐁-𝐗𝐌𝐃🌐",
      serverMessageId: 1001
    }
  }
}, { quoted: ms });

} catch (error) { console.error("FluxAI Error:", error); repondre(❌ Error: ${error.message || "Failed to generate image."}); } });

// =============== STABLE DIFFUSION =============== zokou({ nomCom: "stablediffusion", aliases: ["sdiffusion", "imagine2"], categorie: "ai", reaction: "🚀" }, async (jid, sock, { ms, repondre, arg }) => { const q = arg.join(" "); if (!q) return repondre("❌ Please provide a prompt for the image.");

await repondre("> CREATING IMAGE ...🔥");

try { const url = https://api.siputzx.my.id/api/ai/stable-diffusion?prompt=${encodeURIComponent(q)}; const { data } = await axios.get(url, { responseType: "arraybuffer" });

await sock.sendMessage(jid, {
  image: Buffer.from(data, "binary"),
  caption: `💸 *Image by NEXUS-XMD* 🚀\n✨ Prompt: *${q}*`,
  contextInfo: {
    forwardingScore: 999,
    isForwarded: true,
    forwardedNewsletterMessageInfo: {
      newsletterJid: "120363382023564830@newsletter",
      newsletterName: "🌐𝐁.𝐌.𝐁-𝐗𝐌𝐃🌐",
      serverMessageId: 1002
    }
  }
}, { quoted: ms });

} catch (error) { console.error("StableDiffusion Error:", error); repondre(❌ Error: ${error.message || "Failed to generate image."}); } });

// =============== STABILITY AI =============== zokou({ nomCom: "stabilityai", aliases: ["stability", "imagine3"], categorie: "ai", reaction: "🚀" }, async (jid, sock, { ms, repondre, arg }) => { const q = arg.join(" "); if (!q) return repondre("❌ Please provide a prompt for the image.");

await repondre("> CREATING IMAGE ...🔥");

try { const url = https://api.siputzx.my.id/api/ai/stabilityai?prompt=${encodeURIComponent(q)}; const { data } = await axios.get(url, { responseType: "arraybuffer" });

await sock.sendMessage(jid, {
  image: Buffer.from(data, "binary"),
  caption: `💸 *Generated by NEXUS-XMD* 🚀\n✨ Prompt: *${q}*`,
  contextInfo: {
    forwardingScore: 999,
    isForwarded: true,
    forwardedNewsletterMessageInfo: {
      newsletterJid: "120363382023564830@newsletter",
      newsletterName: "🌐𝐁.𝐌.𝐁-𝐗𝐌𝐃🌐",
      serverMessageId: 1003
    }
  }
}, { quoted: ms });

} catch (error) { console.error("StabilityAI Error:", error); repondre(❌ Error: ${error.message || "Failed to generate image."}); } });

  
