const { zokou } = require("../framework/zokou");
const axios = require("axios");

// =============== FLUX AI ===============
zokou({
  nomCom: "fluxai",
  aliases: ["flux", "imagine"],
  categorie: "ai",
  reaction: "🚀"
}, async (jid, sock, { ms, repondre, arg }) => {
  const q = arg.join(" ");
  if (!q) return repondre("❌ Please provide a prompt for the image.");

  await repondre("> *CREATING IMAGE ...🔥*");

  try {
    const url = `https://api.siputzx.my.id/api/ai/flux?prompt=${encodeURIComponent(q)}`;
    const { data } = await axios.get(url, { responseType: "arraybuffer" });

    await sock.sendMessage(jid, {
      image: Buffer.from(data, "binary"),
      caption: `💸 *Imagine Generated By 𝗕.𝗠.𝗕-𝗧𝗘𝗖𝗛* 🚀\n✨ Prompt: *${q}*`
    }, { quoted: ms });

  } catch (error) {
    console.error("FluxAI Error:", error);
    repondre(`❌ Error: ${error.message || "Failed to generate image."}`);
  }
});

// =============== STABLE DIFFUSION ===============
zokou({
  nomCom: "stablediffusion",
  aliases: ["sdiffusion", "imagine2"],
  categorie: "ai",
  reaction: "🚀"
}, async (jid, sock, { ms, repondre, arg }) => {
  const q = arg.join(" ");
  if (!q) return repondre("❌ Please provide a prompt for the image.");

  await repondre("> *CREATING IMAGE ...🔥*");

  try {
    const url = `https://api.siputzx.my.id/api/ai/stable-diffusion?prompt=${encodeURIComponent(q)}`;
    const { data } = await axios.get(url, { responseType: "arraybuffer" });

    await sock.sendMessage(jid, {
      image: Buffer.from(data, "binary"),
      caption: `💸 *Image by 𝗕.𝗠.𝗕-𝗧𝗘𝗖𝗛* 🚀\n✨ Prompt: *${q}*`
    }, { quoted: ms });

  } catch (error) {
    console.error("StableDiffusion Error:", error);
    repondre(`❌ Error: ${error.message || "Failed to generate image."}`);
  }
});

// =============== STABILITY AI ===============
zokou({
  nomCom: "stabilityai",
  aliases: ["stability", "imagine3"],
  categorie: "ai",
  reaction: "🚀"
}, async (jid, sock, { ms, repondre, arg }) => {
  const q = arg.join(" ");
  if (!q) return repondre("❌ Please provide a prompt for the image.");

  await repondre("> *CREATING IMAGE ...🔥*");

  try {
    const url = `https://api.siputzx.my.id/api/ai/stabilityai?prompt=${encodeURIComponent(q)}`;
    const { data } = await axios.get(url, { responseType: "arraybuffer" });

    await sock.sendMessage(jid, {
      image: Buffer.from(data, "binary"),
      caption: `💸 *Generated by 𝗕.𝗠.𝗕-𝗧𝗘𝗖𝗛* 🚀\n✨ Prompt: *${q}*`
    }, { quoted: ms });

  } catch (error) {
    console.error("StabilityAI Error:", error);
    repondre(`❌ Error: ${error.message || "Failed to generate image."}`);
  }
});
