const audioMap = {
  "hey": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/hey.mp3",
  "hi": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/hey.mp3",
  "hello": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/hello.mp3",
  "mambo": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/hello.mp3",
  "niaje": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/hey.mp3",
  "morning": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/goodmorning.mp3",
  "goodmorning": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/goodmorning.mp3",
  "weka up": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/goodmorning.mp3",
  "night": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/goodnight.mp3",
  "goodnight": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/goodnight.mp3",
  "sleep": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/goodnight.mp3",
  "oyaah": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/mkuu.mp3",
  "mkuu": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/mkuu.mp3",
  "good afternoon": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/goodafternoon.mp3",
  "vp": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/mkuu.mp3",
  "yoo": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/mkuu.mp3",
  "bro": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/mkuu.mp3",
  "usiku mwema": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/goodnight.mp3",
  "b.m.b": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/bmb.mp3",
  "bmb": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/bmb.mp3",
  "nova": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/bmb.mp3",
  "bot": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/morio.mp3",
  "whatsapp bot": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/morio.mp3",
  "tech": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/bmb.mp3",
  "good evening": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/goodevening.mp3",
  "evening": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/goodevening.mp3",
  "goodevening": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/goodevening.mp3",
  "darling": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/darling.mp3",
  "beb": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/darling.mp3",
  "mpenzi": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/darling.mp3",
  "afternoon": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/goodafternoon.mp3",
  "jion": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/goodafternoon.mp3",
  "kaka": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/kaka.mp3",
  "ndugu": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/kaka.mp3",
  "group": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/morio.mp3",
  "i need bot": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/morio.mp3",
  "kijina": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/kaka.mp3",
  "ozah": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/kaka.mp3",
  "ozaah": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/kaka.mp3",
  "oyah": "https://github.com/novaxmd/BMB-XMD-DATA/raw/refs/heads/main/audio/kaka.mp3"
};

module.exports = audioMap;
